name: Build & Test 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 📂
        run: dotnet restore src/Web.Api

      - name: Build 🧱
        run: dotnet build src/Web.Api --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test src/Web.Api --configuration Release --no-build
